### ISSUE TITLE
Cross-compile the CLI

### ISSUE THREAD

**Issue by gtramontina** [fgrehm/devstep-cli#26]
I was giving `devstep` a try on my OSX (with boot2docker) and got stuck on the CLI dependency... Apparently release v0.1.0 is linux-only. A (very quick) search got me here: https://github.com/davecheney/golang-crosscompile -- do you think this is something to look at?

Cheers.

**Comment by filipesperandio** [comment]
I am the second. Can't compile, everything is linux specific. :(

**Comment by fgrehm** [comment]
I'll give u guys a precompiled macos executable tomorrow ;-)

--
Fábio Rehm
Sent on the run

**Comment by fgrehm** [comment]
I was able to use devstep on an OSX machine thanks to [dinghy](https://github.com/codekitchen/dinghy), an executable should be available on the releases page once the travis job is done and the new docker image is build on the hub :fireworks: :beers:
