### ISSUE TITLE
Docker 1.10 : Content-Type specified (plain/text) must be 'application/json'

### ISSUE THREAD

**Issue by sebastienbeau** [fgrehm/devstep-cli#43]
Hi @fgrehm 
A member of my team had an issue with the last version of docker and devstep.
It seem that the issue impact a many project : https://github.com/fsouza/go-dockerclient/issues/455

**Comment by fgrehm** [comment]
Sorry but I'm not having that error on my end =/ The issue you linked was closed back in february and the latest devstep release is from March 9

**Comment by sebastienbeau** [comment]
Really strange I have updated my machine on ubuntu 16.04 and so move to docker Docker version 1.10.3, build 20f81dd
And when I run devstep I have this message and devstep is blocked
devstep hack -p 3333:333 --link f86f15cc975b:odoo
Content-Type specified (plain/text) must be 'application/json'

**Comment by sebastienbeau** [comment]
I am trying to compile my own devstep cli from the code source, so I can test with the last version of the lib.
It's my first time with a go projet ;).
I have installed go, configured my go path
I have run "go get" to get the lib 
I have this error message 
go install: no install location for directory /home/hermes/DEV/go/devstep-cli outside GOPATH
	For more details see: go help gopath


and now I run "make" and I have this message : 
# github.com/fgrehm/devstep-cli/commands
../../../work/src/github.com/fgrehm/devstep-cli/commands/pristine_cmd.go:31: cannot call non-function CleanCmd.Action (type interface {})
../../../work/src/github.com/fgrehm/devstep-cli/commands/pristine_cmd.go:34: cannot call non-function BootstrapCmd.Action (type interface {})
../../../work/src/github.com/fgrehm/devstep-cli/commands/pristine_cmd.go:36: cannot call non-function BuildCmd.Action (type interface {})
Makefile:12 : la recette pour la cible « build » a échouée
make: *** [build] Erreur 2

What did I have done wrong? any idea?

**Comment by rvalyi** [comment]
@fgrehm Hello I confirm I had this issue too. It happens only if you do a devstep build and then a devstep hack. The hack command will then fail until you remove the images of the build (docker rmi -f ...). So a workaround is to use only hack and not build.

**Comment by sebastienbeau** [comment]
I confirm too. If I use devstep build before the hack fail

**Comment by sebastienbeau** [comment]
Note I have try to build devstep using ... devstep  but the go installation fail
